<?php

function sb_form_system_theme_settings_alter($form, &$form_state) {

  if ($form['var']['#value'] != 'theme_settings') {

    $key = preg_replace(array('/^theme_/', '/_settings$/'), '', $form['var']['#value']);

    $themes = list_themes();

    if (isset($themes[$key]->base_themes)) {

      $theme_keys = array_keys($themes[$key]->base_themes);

      $theme_keys[] = $key;

    }
    else {

      $theme_keys = array($key);

    }

    foreach ($theme_keys as $theme) {

      $theme_path = drupal_get_path('theme', $theme);

      if (file_exists($theme_path . '/theme-settings.php')) {

        $form_state['build_info']['files'][] = $theme_path . '/theme-settings.php';

      }

    }

  }

}